name: wideint CI

on: [push, pull_request]

jobs:
  windows:
    name: Windows ${{ matrix.config.name }}
    runs-on: windows-2022

    strategy:
      matrix:
        config:
          - name: MSVC x86
            generator: Visual Studio 17 2022
            cmake-flags: -A Win32

          - name: MSVC x64
            generator: Visual Studio 17 2022
            cmake-flags: -A x64

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -G "${{ matrix.config.generator }}" ${{ matrix.config.cmake-flags }} -B build

      - name: Build
        run: cd build && cmake --build . --config Debug

      - name: Test
        run: cd build && ctest -V --output-on-failure --interactive-debug-mode 0 -C Debug

  macos:
    name: macOS ${{ matrix.config.name }}
    runs-on: macos-latest
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    strategy:
      matrix:
        config:
          - name: GCC UBSan
            cc: gcc-11
            cxx: g++-11
            cmake-flags: -DCMAKE_CXX_FLAGS_DEBUG='-g -fsanitize=undefined'

          - name: GCC ASan
            cc: gcc-11
            cxx: g++-11
            cmake-flags: -DCMAKE_CXX_FLAGS_DEBUG='-O1 -g -fsanitize=address -fno-omit-frame-pointer'

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake ${{ matrix.config.cmake-flags }} -DCMAKE_BUILD_TYPE=Debug -B build

      - name: Build
        run: cd build && cmake --build . --verbose

      - name: Test
        run: cd build && ctest -V --output-on-failure --interactive-debug-mode 0
